### ISSUE TITLE
Access Required

### ISSUE THREAD

**Issue by hhtrieu0108** [AubrynnReina/Web_Scrapping#1]
Dear Chanh, Im Tide.
I want to pull request to your web anime repository. So can you give me the access. Like add me to your repository. I promises don't do anything. Just sometime I want to do something to improve or review someone code to learn more from them (in this situation is you 👍 ). Hope to be accessed

**Comment by hhtrieu0108** [comment]
I think I dont need more :)) I can pull request without access. Thanks. Sorry if my English not good ✌️

**Comment by AubrynnReina** [comment]
Ah, my bad for taking this long to response. Yes, just go ahead with the pull requests. I would appreciate collaborations from here and there.
